name: CI
on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install dependencies
        run: |
          cd apps/api
          composer install --no-interaction --no-progress --no-scripts
      - name: Run tests
        run: |
          cd apps/api
          ./vendor/bin/phpunit

  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          pnpm install
      - name: Run tests
        run: |
          pnpm --filter web test
      - name: Build
        run: |
          pnpm --filter web build

  # Vercel & Laravel Cloud は Git 連携で自動デプロイ (別途設定不要)
